name: CCPi-Users-NXCT-Manchester
channels:
    - conda-forge
    - https://software.repos.intel.com/python/conda
    - ccpi/label/dev
dependencies:
    - python=3.10
    - ipython
    - ipykernel
    - ipyevents=2.0.1
    - ipympl=0.9.1
    - ipywidgets=7.7.0
    - jupyterlab=3.4
    - mpl-interactions=0.22.0        
    - numpy
    # - SimpleITK
    - matplotlib
    - cil=24.2.0
    - ipp=2021.12
    - ccpi-regulariser
    - tigre
    - astra-toolbox=*=cuda*
    - cudatoolkit
    - k3d
